---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      ansible.builtin.debug:
        msg: "Hello {{ user_name }}!"

- name: Ansible facts playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Define custom facts
      ansible.builtin.set_fact:
        server_role: "frontend"

    - name: Use custom and built-in fact
      ansible.builtin.debug:
        msg: "The {{ ansible_hostname }} is assigned the role {{ server_role }}"